
// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.7.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'output_directory': '.',
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'ufl_file': ['introduction.py'],
//   'verbosity': 30,
//   'visualise': False}

#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>



// Code for element element_2382339f5038df5374caf03b25fca8de5796175d






ufcx_finite_element element_2382339f5038df5374caf03b25fca8de5796175d =
{
  .signature = "Basix element (P, triangle, 1, gll_warped, unset, False)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 3,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_2382339f5038df5374caf03b25fca8de5796175d

// Code for dofmap dofmap_2382339f5038df5374caf03b25fca8de5796175d



int entity_dofs_dofmap_2382339f5038df5374caf03b25fca8de5796175d[3] = {0, 1, 2};

int entity_dof_offsets_dofmap_2382339f5038df5374caf03b25fca8de5796175d[8] = {0, 1, 2, 3, 3, 3, 3, 3};

int entity_closure_dofs_dofmap_2382339f5038df5374caf03b25fca8de5796175d[12] = {0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2};

int entity_closure_dof_offsets_dofmap_2382339f5038df5374caf03b25fca8de5796175d[8] = {0, 1, 2, 3, 5, 7, 9, 12};

ufcx_dofmap dofmap_2382339f5038df5374caf03b25fca8de5796175d =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 1, gll_warped, unset, False)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 1,
  .entity_dofs = entity_dofs_dofmap_2382339f5038df5374caf03b25fca8de5796175d,
  .entity_dof_offsets = entity_dof_offsets_dofmap_2382339f5038df5374caf03b25fca8de5796175d,
  .entity_closure_dofs = entity_closure_dofs_dofmap_2382339f5038df5374caf03b25fca8de5796175d,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_2382339f5038df5374caf03b25fca8de5796175d,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_2382339f5038df5374caf03b25fca8de5796175d
