
// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.7.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'output_directory': '/root/shared/src',
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'ufl_file': ['/root/shared/src/ufl_formulation.py'],
//   'verbosity': 30,
//   'visualise': True}

#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>



// Code for element element_d4076abb8f1620b9a53fe2cc4775a36a983b4491






ufcx_finite_element element_d4076abb8f1620b9a53fe2cc4775a36a983b4491 =
{
  .signature = "Basix element (P, triangle, 1, gll_warped, unset, False)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 3,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_d4076abb8f1620b9a53fe2cc4775a36a983b4491

// Code for element element_970575127bb6827bf4cf0fd55619bb9271936f4e

int value_shape_element_970575127bb6827bf4cf0fd55619bb9271936f4e[1] = {2};
int reference_value_shape_element_970575127bb6827bf4cf0fd55619bb9271936f4e[1] = {2};
ufcx_finite_element* sub_elements_element_970575127bb6827bf4cf0fd55619bb9271936f4e[2] = {&element_d4076abb8f1620b9a53fe2cc4775a36a983b4491, &element_d4076abb8f1620b9a53fe2cc4775a36a983b4491};


ufcx_finite_element element_970575127bb6827bf4cf0fd55619bb9271936f4e =
{
  .signature = "blocked element (Basix element (P, triangle, 1, gll_warped, unset, False), (2,))",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 6,
  .value_rank = 1,
  .value_shape = value_shape_element_970575127bb6827bf4cf0fd55619bb9271936f4e,
  .value_size = 2,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_970575127bb6827bf4cf0fd55619bb9271936f4e,
  .reference_value_size = 2,
  .degree = 1,
  .block_size = 2,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 2,
  .sub_elements = sub_elements_element_970575127bb6827bf4cf0fd55619bb9271936f4e,
  .custom_element = NULL
};

// End of code for element element_970575127bb6827bf4cf0fd55619bb9271936f4e

// Code for element element_8d4119401072738022d0ce765272f81e8050b30b






ufcx_finite_element element_8d4119401072738022d0ce765272f81e8050b30b =
{
  .signature = "Basix element (P, triangle, 2, gll_warped, unset, True)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 6,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 2,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = true,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_8d4119401072738022d0ce765272f81e8050b30b

// Code for element element_147d06faedb07b84e00f1285ddb8f4aefa262c23






ufcx_finite_element element_147d06faedb07b84e00f1285ddb8f4aefa262c23 =
{
  .signature = "Basix element (P, triangle, 0, gll_warped, unset, True)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 1,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 0,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = true,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_147d06faedb07b84e00f1285ddb8f4aefa262c23

// Code for dofmap dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491



int entity_dofs_dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491[3] = {0, 1, 2};

int entity_dof_offsets_dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491[8] = {0, 1, 2, 3, 3, 3, 3, 3};

int entity_closure_dofs_dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491[12] = {0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2};

int entity_closure_dof_offsets_dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491[8] = {0, 1, 2, 3, 5, 7, 9, 12};

ufcx_dofmap dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491 =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 1, gll_warped, unset, False)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 1,
  .entity_dofs = entity_dofs_dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491,
  .entity_dof_offsets = entity_dof_offsets_dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491,
  .entity_closure_dofs = entity_closure_dofs_dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491

// Code for dofmap dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e

ufcx_dofmap* sub_dofmaps_dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e[2] = {&dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491, &dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491};

int entity_dofs_dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e[3] = {0, 1, 2};

int entity_dof_offsets_dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e[8] = {0, 1, 2, 3, 3, 3, 3, 3};

int entity_closure_dofs_dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e[12] = {0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2};

int entity_closure_dof_offsets_dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e[8] = {0, 1, 2, 3, 5, 7, 9, 12};

ufcx_dofmap dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e =
{
  .signature = "FFCx dofmap for blocked element (Basix element (P, triangle, 1, gll_warped, unset, False), (2,))",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 2,
  .entity_dofs = entity_dofs_dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e,
  .entity_dof_offsets = entity_dof_offsets_dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e,
  .entity_closure_dofs = entity_closure_dofs_dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e,
  .num_sub_dofmaps = 2,
  .sub_dofmaps = sub_dofmaps_dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e
};

// End of code for dofmap dofmap_970575127bb6827bf4cf0fd55619bb9271936f4e

// Code for dofmap dofmap_8d4119401072738022d0ce765272f81e8050b30b



int entity_dofs_dofmap_8d4119401072738022d0ce765272f81e8050b30b[6] = {0, 1, 2, 3, 4, 5};

int entity_dof_offsets_dofmap_8d4119401072738022d0ce765272f81e8050b30b[8] = {0, 0, 0, 0, 0, 0, 0, 6};

int entity_closure_dofs_dofmap_8d4119401072738022d0ce765272f81e8050b30b[6] = {0, 1, 2, 3, 4, 5};

int entity_closure_dof_offsets_dofmap_8d4119401072738022d0ce765272f81e8050b30b[8] = {0, 0, 0, 0, 0, 0, 0, 6};

ufcx_dofmap dofmap_8d4119401072738022d0ce765272f81e8050b30b =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 2, gll_warped, unset, True)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 6,
  .block_size = 1,
  .entity_dofs = entity_dofs_dofmap_8d4119401072738022d0ce765272f81e8050b30b,
  .entity_dof_offsets = entity_dof_offsets_dofmap_8d4119401072738022d0ce765272f81e8050b30b,
  .entity_closure_dofs = entity_closure_dofs_dofmap_8d4119401072738022d0ce765272f81e8050b30b,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_8d4119401072738022d0ce765272f81e8050b30b,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_8d4119401072738022d0ce765272f81e8050b30b

// Code for dofmap dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23



int entity_dofs_dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23[1] = {0};

int entity_dof_offsets_dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23[8] = {0, 0, 0, 0, 0, 0, 0, 1};

int entity_closure_dofs_dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23[1] = {0};

int entity_closure_dof_offsets_dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23[8] = {0, 0, 0, 0, 0, 0, 0, 1};

ufcx_dofmap dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23 =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 0, gll_warped, unset, True)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 1,
  .block_size = 1,
  .entity_dofs = entity_dofs_dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23,
  .entity_dof_offsets = entity_dof_offsets_dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23,
  .entity_closure_dofs = entity_closure_dofs_dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23

// Code for integral integral_7c458cb5d2392dea99f2f3bfc6036ad00809d670

void tabulate_tensor_integral_7c458cb5d2392dea99f2f3bfc6036ad00809d670(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
// Quadrature rules
static const double weights_39d[6] = {0.054975871827661, 0.054975871827661, 0.054975871827661, 0.1116907948390055, 0.1116907948390055, 0.1116907948390055};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const double FE4_C0_D10_Q39d[1][1][1][3] = {{{{-1.0, 1.0, 0.0}}}};
static const double FE4_C1_D01_Q39d[1][1][1][3] = {{{{-1.0, 0.0, 1.0}}}};
static const double FE6_C0_Q39d[1][1][6][6] = {{{{-0.07480380774819603, 0.5176323419876736, -0.07480380774819671, 0.2992152309927871, 0.03354481152314834, 0.2992152309927839},
  {-0.07480380774819613, -0.0748038077481966, 0.5176323419876735, 0.2992152309927871, 0.2992152309927838, 0.03354481152314828},
  {0.5176323419876713, -0.0748038077481967, -0.07480380774819674, 0.03354481152314866, 0.2992152309927869, 0.2992152309927868},
  {-0.04820837781551195, -0.08473049309397784, -0.04820837781551192, 0.1928335112620479, 0.7954802262009061, 0.1928335112620478},
  {-0.04820837781551193, -0.048208377815512, -0.08473049309397786, 0.1928335112620479, 0.192833511262048, 0.7954802262009062},
  {-0.08473049309397794, -0.04820837781551188, -0.04820837781551195, 0.7954802262009061, 0.1928335112620479, 0.1928335112620479}}}};
// Quadrature loop independent computations for quadrature rule 39d
double J_c0 = 0.0;
double J_c3 = 0.0;
double J_c1 = 0.0;
double J_c2 = 0.0;
for (int ic = 0; ic < 3; ++ic)
{
  J_c0 += coordinate_dofs[3 * ic] * FE4_C0_D10_Q39d[0][0][0][ic];
  J_c3 += coordinate_dofs[3 * ic + 1] * FE4_C1_D01_Q39d[0][0][0][ic];
  J_c1 += coordinate_dofs[3 * ic] * FE4_C1_D01_Q39d[0][0][0][ic];
  J_c2 += coordinate_dofs[3 * ic + 1] * FE4_C0_D10_Q39d[0][0][0][ic];
}
double sp_39d[4];
sp_39d[0] = J_c0 * J_c3;
sp_39d[1] = J_c1 * J_c2;
sp_39d[2] = sp_39d[0] - sp_39d[1];
sp_39d[3] = fabs(sp_39d[2]);
for (int iq = 0; iq < 6; ++iq)
{
  double fw0 = sp_39d[3] * weights_39d[iq];
  double t0[6];
  for (int i = 0; i < 6; ++i)
  {
    t0[i] = fw0 * FE6_C0_Q39d[0][0][iq][i];
  }
  for (int i = 0; i < 6; ++i)
  {
    for (int j = 0; j < 6; ++j)
    {
      A[6 * i + j] += FE6_C0_Q39d[0][0][iq][j] * t0[i];
    }
  }
}

}



ufcx_integral integral_7c458cb5d2392dea99f2f3bfc6036ad00809d670 =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor_float64 = tabulate_tensor_integral_7c458cb5d2392dea99f2f3bfc6036ad00809d670,
  .needs_facet_permutations = false,
  .coordinate_element = &element_970575127bb6827bf4cf0fd55619bb9271936f4e,
};

// End of code for integral integral_7c458cb5d2392dea99f2f3bfc6036ad00809d670

// Code for integral integral_d610b8146bafccb34b163689049ecb674ac43814

void tabulate_tensor_integral_d610b8146bafccb34b163689049ecb674ac43814(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
// Quadrature rules
static const double weights_7a4[6] = {0.08333333333333333, 0.08333333333333333, 0.08333333333333333, 0.08333333333333333, 0.08333333333333333, 0.08333333333333333};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const double FE3_C0_Q7a4[1][1][6][3] = {{{{0.1090390090728771, 0.659027622374092, 0.231933368553031},
  {0.2319333685530311, 0.659027622374092, 0.109039009072877},
  {0.109039009072877, 0.231933368553031, 0.6590276223740918},
  {0.6590276223740921, 0.231933368553031, 0.109039009072877},
  {0.231933368553031, 0.109039009072877, 0.6590276223740918},
  {0.6590276223740921, 0.1090390090728769, 0.231933368553031}}}};
static const double FE4_C0_D10_Q7a4[1][1][1][3] = {{{{-1.0, 1.0, 0.0}}}};
static const double FE4_C1_D01_Q7a4[1][1][1][3] = {{{{-1.0, 0.0, 1.0}}}};
static const double FE5_C0_Q7a4[1][1][6][6] = {{{{-0.08525999807368716, 0.2096071917300056, -0.1243471936563188, 0.6114019857068721, 0.1011591387118275, 0.2874388755813007},
  {-0.1243471936563188, 0.2096071917300055, -0.08525999807368713, 0.2874388755813008, 0.1011591387118276, 0.6114019857068723},
  {-0.0852599980736872, -0.1243471936563187, 0.2096071917300056, 0.6114019857068721, 0.2874388755813007, 0.1011591387118275},
  {0.2096071917300056, -0.1243471936563188, -0.08525999807368713, 0.1011591387118276, 0.2874388755813008, 0.6114019857068723},
  {-0.1243471936563188, -0.08525999807368707, 0.2096071917300056, 0.2874388755813007, 0.6114019857068721, 0.1011591387118275},
  {0.2096071917300057, -0.08525999807368712, -0.1243471936563187, 0.1011591387118275, 0.6114019857068722, 0.2874388755813007}}}};
// Quadrature loop independent computations for quadrature rule 7a4
double J_c0 = 0.0;
double J_c3 = 0.0;
double J_c1 = 0.0;
double J_c2 = 0.0;
for (int ic = 0; ic < 3; ++ic)
{
  J_c0 += coordinate_dofs[3 * ic] * FE4_C0_D10_Q7a4[0][0][0][ic];
  J_c3 += coordinate_dofs[3 * ic + 1] * FE4_C1_D01_Q7a4[0][0][0][ic];
  J_c1 += coordinate_dofs[3 * ic] * FE4_C1_D01_Q7a4[0][0][0][ic];
  J_c2 += coordinate_dofs[3 * ic + 1] * FE4_C0_D10_Q7a4[0][0][0][ic];
}
double sp_7a4[4];
sp_7a4[0] = J_c0 * J_c3;
sp_7a4[1] = J_c1 * J_c2;
sp_7a4[2] = sp_7a4[0] - sp_7a4[1];
sp_7a4[3] = fabs(sp_7a4[2]);
for (int iq = 0; iq < 6; ++iq)
{
  // Quadrature loop body setup for quadrature rule 7a4
  // Varying computations for quadrature rule 7a4
  double w1 = 0.0;
  for (int ic = 0; ic < 3; ++ic)
  {
    w1 += w[1 + ic] * FE3_C0_Q7a4[0][0][iq][ic];
  }
  double sv_7a4[2];
  sv_7a4[0] = w[0] / w1;
  sv_7a4[1] = sv_7a4[0] * sp_7a4[3];
  double fw0 = sv_7a4[1] * weights_7a4[iq];
  for (int i = 0; i < 6; ++i)
  {
    A[i] += fw0 * FE5_C0_Q7a4[0][0][iq][i];
  }
}

}

bool enabled_coefficients_integral_d610b8146bafccb34b163689049ecb674ac43814[2] = {1, 1};

ufcx_integral integral_d610b8146bafccb34b163689049ecb674ac43814 =
{
  .enabled_coefficients = enabled_coefficients_integral_d610b8146bafccb34b163689049ecb674ac43814,
  .tabulate_tensor_float64 = tabulate_tensor_integral_d610b8146bafccb34b163689049ecb674ac43814,
  .needs_facet_permutations = false,
  .coordinate_element = &element_970575127bb6827bf4cf0fd55619bb9271936f4e,
};

// End of code for integral integral_d610b8146bafccb34b163689049ecb674ac43814

// Code for form form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8


ufcx_dofmap* dofmaps_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8[2] = {&dofmap_8d4119401072738022d0ce765272f81e8050b30b, &dofmap_8d4119401072738022d0ce765272f81e8050b30b};
ufcx_finite_element* finite_elements_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8[2] = {&element_8d4119401072738022d0ce765272f81e8050b30b, &element_8d4119401072738022d0ce765272f81e8050b30b};
int form_integral_offsets_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8[4] = {0, 1, 1, 1};
static ufcx_integral* form_integrals_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8[1] = {&integral_7c458cb5d2392dea99f2f3bfc6036ad00809d670};
int form_integral_ids_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8[1] = {-1};

// Return a list of the coefficient names.
const char** coefficient_name_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8(void)
{
return NULL;
}

// Return a list of the constant names.
const char** constant_name_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8(void)
{
return NULL;
}

ufcx_form form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8 =
{

  .signature = "100eae67a1d4a17ba3a30070349d7c552775172912108b2a5f8028edcd11451f465e7653a47cc750521d2af6b26b794904dae59d21046a930892e6d949453182",
  .rank = 2,
  .num_coefficients = 0,
  .num_constants = 0,
  .original_coefficient_position = NULL,

  .coefficient_name_map = coefficient_name_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8,
  .constant_name_map = constant_name_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8,

  .finite_elements = finite_elements_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8,
  .dofmaps = dofmaps_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8,

  .form_integrals = form_integrals_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8,
  .form_integral_ids = form_integral_ids_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8,
  .form_integral_offsets = form_integral_offsets_form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8
};

// Alias name
ufcx_form* form_ufl_formulation_a = &form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8;

ufcx_function_space* functionspace_form_ufl_formulation_a(const char* function_name)
{
static ufcx_function_space functionspace_v =
{
.finite_element = &element_8d4119401072738022d0ce765272f81e8050b30b,
.dofmap = &dofmap_8d4119401072738022d0ce765272f81e8050b30b,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 0
};
static ufcx_function_space functionspace_u =
{
.finite_element = &element_8d4119401072738022d0ce765272f81e8050b30b,
.dofmap = &dofmap_8d4119401072738022d0ce765272f81e8050b30b,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 0
};
if (strcmp(function_name, "v") == 0) return &functionspace_v;
if (strcmp(function_name, "u") == 0) return &functionspace_u;
return NULL;

}

// End of code for form form_a805ca088d9be36dfe4f132b6d99b6c1afc19bb8

// Code for form form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc

int original_coefficient_position_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc[2] = {0, 1};
ufcx_dofmap* dofmaps_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc[3] = {&dofmap_8d4119401072738022d0ce765272f81e8050b30b, &dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23, &dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491};
ufcx_finite_element* finite_elements_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc[3] = {&element_8d4119401072738022d0ce765272f81e8050b30b, &element_147d06faedb07b84e00f1285ddb8f4aefa262c23, &element_d4076abb8f1620b9a53fe2cc4775a36a983b4491};
int form_integral_offsets_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc[4] = {0, 1, 1, 1};
static ufcx_integral* form_integrals_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc[1] = {&integral_d610b8146bafccb34b163689049ecb674ac43814};
int form_integral_ids_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc[1] = {-1};

// Return a list of the coefficient names.
const char** coefficient_name_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc(void)
{
static const char* names[2] = {"f", "g"};
return names;
}

// Return a list of the constant names.
const char** constant_name_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc(void)
{
return NULL;
}

ufcx_form form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc =
{

  .signature = "1052c20f48bf09236076e143a05ae6053cb8949e0757ea5581562b9c58f56a83e3b1b5793481806848d7a99252cbd458b87d603ba6f81346bc93022aca006c0c",
  .rank = 1,
  .num_coefficients = 2,
  .num_constants = 0,
  .original_coefficient_position = original_coefficient_position_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc,

  .coefficient_name_map = coefficient_name_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc,
  .constant_name_map = constant_name_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc,

  .finite_elements = finite_elements_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc,
  .dofmaps = dofmaps_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc,

  .form_integrals = form_integrals_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc,
  .form_integral_ids = form_integral_ids_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc,
  .form_integral_offsets = form_integral_offsets_form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc
};

// Alias name
ufcx_form* form_ufl_formulation_L = &form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc;

ufcx_function_space* functionspace_form_ufl_formulation_L(const char* function_name)
{
static ufcx_function_space functionspace_v =
{
.finite_element = &element_8d4119401072738022d0ce765272f81e8050b30b,
.dofmap = &dofmap_8d4119401072738022d0ce765272f81e8050b30b,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 0
};
static ufcx_function_space functionspace_f =
{
.finite_element = &element_147d06faedb07b84e00f1285ddb8f4aefa262c23,
.dofmap = &dofmap_147d06faedb07b84e00f1285ddb8f4aefa262c23,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 0
};
static ufcx_function_space functionspace_g =
{
.finite_element = &element_d4076abb8f1620b9a53fe2cc4775a36a983b4491,
.dofmap = &dofmap_d4076abb8f1620b9a53fe2cc4775a36a983b4491,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 0
};
if (strcmp(function_name, "v") == 0) return &functionspace_v;
if (strcmp(function_name, "f") == 0) return &functionspace_f;
if (strcmp(function_name, "g") == 0) return &functionspace_g;
return NULL;

}

// End of code for form form_57b14fd82734fa4ba8d4bb795d8df6c7beefb6fc
