// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.6.0.
//
// This code was generated with the following options:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '/root/shared/src',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['/root/shared/src/ufl_formulation.py'],
//   'verbosity': 30,
//   'visualise': True}


#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>

// Code for element element_758f5686b8ddc30826def622d3335ea7a2de6406






ufcx_finite_element element_758f5686b8ddc30826def622d3335ea7a2de6406 =
{
  .signature = "Basix element (P, triangle, 1, gll_warped, unset, False)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 3,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_758f5686b8ddc30826def622d3335ea7a2de6406

// Code for element element_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7

int value_shape_element_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7[1] = { 2 };
int reference_value_shape_element_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7[1] = { 2 };
ufcx_finite_element* sub_elements_element_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7[2] = { &element_758f5686b8ddc30826def622d3335ea7a2de6406, &element_758f5686b8ddc30826def622d3335ea7a2de6406 };


ufcx_finite_element element_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7 =
{
  .signature = "VectorElement(Basix element (P, triangle, 1, gll_warped, unset, False), 2)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 6,
  .value_rank = 1,
  .value_shape = value_shape_element_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7,
  .value_size = 2,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7,
  .reference_value_size = 2,
  .degree = 1,
  .block_size = 2,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 2,
  .sub_elements = sub_elements_element_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7,
  .custom_element = NULL
};

// End of code for element element_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7

// Code for element element_1e49afa206707d093aa7a304ac40b15c9118976c






ufcx_finite_element element_1e49afa206707d093aa7a304ac40b15c9118976c =
{
  .signature = "Basix element (P, triangle, 2, gll_warped, unset, True)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 6,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 2,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = true,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_1e49afa206707d093aa7a304ac40b15c9118976c

// Code for element element_cf15df922a09e79fc4974dae41db8acb96787533






ufcx_finite_element element_cf15df922a09e79fc4974dae41db8acb96787533 =
{
  .signature = "Basix element (P, triangle, 0, gll_warped, unset, True)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 1,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 0,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = true,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_cf15df922a09e79fc4974dae41db8acb96787533

// Code for dofmap dofmap_758f5686b8ddc30826def622d3335ea7a2de6406



void tabulate_entity_dofs_dofmap_758f5686b8ddc30826def622d3335ea7a2de6406(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_758f5686b8ddc30826def622d3335ea7a2de6406(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 1;
    dofs[1] = 2;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    break;
  case 2:
    dofs[0] = 0;
    dofs[1] = 1;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_758f5686b8ddc30826def622d3335ea7a2de6406[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_758f5686b8ddc30826def622d3335ea7a2de6406[4] = { 1, 2, 3, 0 };

ufcx_dofmap dofmap_758f5686b8ddc30826def622d3335ea7a2de6406 =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 1, gll_warped, unset, False)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_758f5686b8ddc30826def622d3335ea7a2de6406,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_758f5686b8ddc30826def622d3335ea7a2de6406,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_758f5686b8ddc30826def622d3335ea7a2de6406,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_758f5686b8ddc30826def622d3335ea7a2de6406,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_758f5686b8ddc30826def622d3335ea7a2de6406

// Code for dofmap dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7

ufcx_dofmap* sub_dofmaps_dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7[2] = { &dofmap_758f5686b8ddc30826def622d3335ea7a2de6406, &dofmap_758f5686b8ddc30826def622d3335ea7a2de6406 };

void tabulate_entity_dofs_dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 1;
    dofs[1] = 2;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    break;
  case 2:
    dofs[0] = 0;
    dofs[1] = 1;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7[4] = { 1, 2, 3, 0 };

ufcx_dofmap dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7 =
{
  .signature = "FFCx dofmap for VectorElement(Basix element (P, triangle, 1, gll_warped, unset, False), 2)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 2,
  .num_entity_dofs = num_entity_dofs_dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7,
  .num_sub_dofmaps = 2,
  .sub_dofmaps = sub_dofmaps_dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7
};

// End of code for dofmap dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7

// Code for dofmap dofmap_1e49afa206707d093aa7a304ac40b15c9118976c



void tabulate_entity_dofs_dofmap_1e49afa206707d093aa7a304ac40b15c9118976c(int* restrict dofs, int d, int i)
{
switch (d)
{
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 3;
    dofs[4] = 4;
    dofs[5] = 5;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_1e49afa206707d093aa7a304ac40b15c9118976c(int* restrict dofs, int d, int i)
{
switch (d)
{
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 3;
    dofs[4] = 4;
    dofs[5] = 5;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_1e49afa206707d093aa7a304ac40b15c9118976c[4] = { 0, 0, 6, 0 };

int num_entity_closure_dofs_dofmap_1e49afa206707d093aa7a304ac40b15c9118976c[4] = { 0, 0, 6, 0 };

ufcx_dofmap dofmap_1e49afa206707d093aa7a304ac40b15c9118976c =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 2, gll_warped, unset, True)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 6,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_1e49afa206707d093aa7a304ac40b15c9118976c,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_1e49afa206707d093aa7a304ac40b15c9118976c,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_1e49afa206707d093aa7a304ac40b15c9118976c,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_1e49afa206707d093aa7a304ac40b15c9118976c,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_1e49afa206707d093aa7a304ac40b15c9118976c

// Code for dofmap dofmap_cf15df922a09e79fc4974dae41db8acb96787533



void tabulate_entity_dofs_dofmap_cf15df922a09e79fc4974dae41db8acb96787533(int* restrict dofs, int d, int i)
{
switch (d)
{
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_cf15df922a09e79fc4974dae41db8acb96787533(int* restrict dofs, int d, int i)
{
switch (d)
{
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_cf15df922a09e79fc4974dae41db8acb96787533[4] = { 0, 0, 1, 0 };

int num_entity_closure_dofs_dofmap_cf15df922a09e79fc4974dae41db8acb96787533[4] = { 0, 0, 1, 0 };

ufcx_dofmap dofmap_cf15df922a09e79fc4974dae41db8acb96787533 =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 0, gll_warped, unset, True)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 1,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_cf15df922a09e79fc4974dae41db8acb96787533,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_cf15df922a09e79fc4974dae41db8acb96787533,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_cf15df922a09e79fc4974dae41db8acb96787533,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_cf15df922a09e79fc4974dae41db8acb96787533,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_cf15df922a09e79fc4974dae41db8acb96787533

// Code for integral integral_d6d1f05c892850147487cbd2aced82d778f6f49d

void tabulate_tensor_integral_d6d1f05c892850147487cbd2aced82d778f6f49d(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
  // Quadrature rules
  static const double weights_39d[6] = { 0.054975871827661, 0.054975871827661, 0.054975871827661, 0.1116907948390055, 0.1116907948390055, 0.1116907948390055 };
  // Precomputed values of basis functions and precomputations
  // FE* dimensions: [permutation][entities][points][dofs]
  static const double FE4_C0_D10_Q39d[1][1][1][3] = { { { { -1.0, 1.0, 0.0 } } } };
  static const double FE4_C1_D01_Q39d[1][1][1][3] = { { { { -1.0, 0.0, 1.0 } } } };
  static const double FE6_C0_Q39d[1][1][6][6] =
    { { { { -0.07480380774819603, 0.5176323419876736, -0.07480380774819671, 0.2992152309927871, 0.03354481152314834, 0.2992152309927839 },
          { -0.07480380774819613, -0.0748038077481966, 0.5176323419876735, 0.2992152309927871, 0.2992152309927838, 0.03354481152314828 },
          { 0.5176323419876713, -0.0748038077481967, -0.07480380774819674, 0.03354481152314866, 0.2992152309927869, 0.2992152309927868 },
          { -0.04820837781551195, -0.08473049309397784, -0.04820837781551192, 0.1928335112620479, 0.7954802262009061, 0.1928335112620478 },
          { -0.04820837781551193, -0.048208377815512, -0.08473049309397786, 0.1928335112620479, 0.192833511262048, 0.7954802262009062 },
          { -0.08473049309397794, -0.04820837781551188, -0.04820837781551195, 0.7954802262009061, 0.1928335112620479, 0.1928335112620479 } } } };
  // Quadrature loop independent computations for quadrature rule 39d
  double J_c0 = 0.0;
  double J_c3 = 0.0;
  double J_c1 = 0.0;
  double J_c2 = 0.0;
  for (int ic = 0; ic < 3; ++ic)
  {
    J_c0 += coordinate_dofs[ic * 3] * FE4_C0_D10_Q39d[0][0][0][ic];
    J_c3 += coordinate_dofs[ic * 3 + 1] * FE4_C1_D01_Q39d[0][0][0][ic];
    J_c1 += coordinate_dofs[ic * 3] * FE4_C1_D01_Q39d[0][0][0][ic];
    J_c2 += coordinate_dofs[ic * 3 + 1] * FE4_C0_D10_Q39d[0][0][0][ic];
  }
  double sp_39d[4];
  sp_39d[0] = J_c0 * J_c3;
  sp_39d[1] = J_c1 * J_c2;
  sp_39d[2] = sp_39d[0] + -1 * sp_39d[1];
  sp_39d[3] = fabs(sp_39d[2]);
  for (int iq = 0; iq < 6; ++iq)
  {
    const double fw0 = sp_39d[3] * weights_39d[iq];
    double t0[6];
    for (int i = 0; i < 6; ++i)
      t0[i] = fw0 * FE6_C0_Q39d[0][0][iq][i];
    for (int i = 0; i < 6; ++i)
      for (int j = 0; j < 6; ++j)
        A[6 * i + j] += FE6_C0_Q39d[0][0][iq][j] * t0[i];
  }
}



ufcx_integral integral_d6d1f05c892850147487cbd2aced82d778f6f49d =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor_float64 = tabulate_tensor_integral_d6d1f05c892850147487cbd2aced82d778f6f49d,
  .needs_facet_permutations = false,
  .coordinate_element = &element_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7,
};

// End of code for integral integral_d6d1f05c892850147487cbd2aced82d778f6f49d

// Code for integral integral_a85408121493aa38ac6bbaa3b690511a8a9f5c0c

void tabulate_tensor_integral_a85408121493aa38ac6bbaa3b690511a8a9f5c0c(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
  // Quadrature rules
  static const double weights_7a4[6] = { 0.08333333333333333, 0.08333333333333333, 0.08333333333333333, 0.08333333333333333, 0.08333333333333333, 0.08333333333333333 };
  // Precomputed values of basis functions and precomputations
  // FE* dimensions: [permutation][entities][points][dofs]
  static const double FE3_C0_Q7a4[1][1][6][3] =
    { { { { 0.1090390090728771, 0.659027622374092, 0.231933368553031 },
          { 0.2319333685530311, 0.659027622374092, 0.109039009072877 },
          { 0.109039009072877, 0.231933368553031, 0.6590276223740918 },
          { 0.6590276223740921, 0.231933368553031, 0.109039009072877 },
          { 0.231933368553031, 0.109039009072877, 0.6590276223740918 },
          { 0.6590276223740921, 0.1090390090728769, 0.231933368553031 } } } };
  static const double FE4_C0_D10_Q7a4[1][1][1][3] = { { { { -1.0, 1.0, 0.0 } } } };
  static const double FE4_C1_D01_Q7a4[1][1][1][3] = { { { { -1.0, 0.0, 1.0 } } } };
  static const double FE5_C0_Q7a4[1][1][6][6] =
    { { { { -0.08525999807368716, 0.2096071917300056, -0.1243471936563188, 0.6114019857068721, 0.1011591387118275, 0.2874388755813007 },
          { -0.1243471936563188, 0.2096071917300055, -0.08525999807368713, 0.2874388755813008, 0.1011591387118276, 0.6114019857068723 },
          { -0.0852599980736872, -0.1243471936563187, 0.2096071917300056, 0.6114019857068721, 0.2874388755813007, 0.1011591387118275 },
          { 0.2096071917300056, -0.1243471936563188, -0.08525999807368713, 0.1011591387118276, 0.2874388755813008, 0.6114019857068723 },
          { -0.1243471936563188, -0.08525999807368707, 0.2096071917300056, 0.2874388755813007, 0.6114019857068721, 0.1011591387118275 },
          { 0.2096071917300057, -0.08525999807368712, -0.1243471936563187, 0.1011591387118275, 0.6114019857068722, 0.2874388755813007 } } } };
  // Quadrature loop independent computations for quadrature rule 7a4
  double J_c0 = 0.0;
  double J_c3 = 0.0;
  double J_c1 = 0.0;
  double J_c2 = 0.0;
  for (int ic = 0; ic < 3; ++ic)
  {
    J_c0 += coordinate_dofs[ic * 3] * FE4_C0_D10_Q7a4[0][0][0][ic];
    J_c3 += coordinate_dofs[ic * 3 + 1] * FE4_C1_D01_Q7a4[0][0][0][ic];
    J_c1 += coordinate_dofs[ic * 3] * FE4_C1_D01_Q7a4[0][0][0][ic];
    J_c2 += coordinate_dofs[ic * 3 + 1] * FE4_C0_D10_Q7a4[0][0][0][ic];
  }
  double sp_7a4[4];
  sp_7a4[0] = J_c0 * J_c3;
  sp_7a4[1] = J_c1 * J_c2;
  sp_7a4[2] = sp_7a4[0] + -1 * sp_7a4[1];
  sp_7a4[3] = fabs(sp_7a4[2]);
  for (int iq = 0; iq < 6; ++iq)
  {
    // Quadrature loop body setup for quadrature rule 7a4
    // Varying computations for quadrature rule 7a4
    double w1 = 0.0;
    for (int ic = 0; ic < 3; ++ic)
      w1 += w[1 + ic] * FE3_C0_Q7a4[0][0][iq][ic];
    double sv_7a4[2];
    sv_7a4[0] = w[0] / w1;
    sv_7a4[1] = sv_7a4[0] * sp_7a4[3];
    const double fw0 = sv_7a4[1] * weights_7a4[iq];
    for (int i = 0; i < 6; ++i)
      A[i] += fw0 * FE5_C0_Q7a4[0][0][iq][i];
  }
}

bool enabled_coefficients_integral_a85408121493aa38ac6bbaa3b690511a8a9f5c0c[2] = { false, false };

ufcx_integral integral_a85408121493aa38ac6bbaa3b690511a8a9f5c0c =
{
  .enabled_coefficients = enabled_coefficients_integral_a85408121493aa38ac6bbaa3b690511a8a9f5c0c,
  .tabulate_tensor_float64 = tabulate_tensor_integral_a85408121493aa38ac6bbaa3b690511a8a9f5c0c,
  .needs_facet_permutations = false,
  .coordinate_element = &element_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7,
};

// End of code for integral integral_a85408121493aa38ac6bbaa3b690511a8a9f5c0c

// Code for form form_1b48ed2e66b63f65dfb298e72afaf2238490f388


ufcx_dofmap* dofmaps_form_1b48ed2e66b63f65dfb298e72afaf2238490f388[2] = { &dofmap_1e49afa206707d093aa7a304ac40b15c9118976c, &dofmap_1e49afa206707d093aa7a304ac40b15c9118976c };
ufcx_finite_element* finite_elements_form_1b48ed2e66b63f65dfb298e72afaf2238490f388[2] = { &element_1e49afa206707d093aa7a304ac40b15c9118976c, &element_1e49afa206707d093aa7a304ac40b15c9118976c };

// Return a list of the coefficient names.
const char** coefficient_name_form_1b48ed2e66b63f65dfb298e72afaf2238490f388(void)
{
return NULL;
}

// Return a list of the constant names.
const char** constant_name_form_1b48ed2e66b63f65dfb298e72afaf2238490f388(void)
{
return NULL;
}

int* integral_ids_form_1b48ed2e66b63f65dfb298e72afaf2238490f388(ufcx_integral_type integral_type)
{
static int integral_ids_cell_form_1b48ed2e66b63f65dfb298e72afaf2238490f388[1] = { -1 };
switch (integral_type)
{
case cell:
  return integral_ids_cell_form_1b48ed2e66b63f65dfb298e72afaf2238490f388;
default:
  return NULL;
}
}

int num_integrals_form_1b48ed2e66b63f65dfb298e72afaf2238490f388(ufcx_integral_type integral_type)
{
switch (integral_type)
{
case cell:
  return 1;
case interior_facet:
  return 0;
case exterior_facet:
  return 0;
default:
  return 0;
}
}

ufcx_integral** integrals_form_1b48ed2e66b63f65dfb298e72afaf2238490f388(ufcx_integral_type integral_type)
{
static ufcx_integral* integrals_cell_form_1b48ed2e66b63f65dfb298e72afaf2238490f388[1] = { &integral_d6d1f05c892850147487cbd2aced82d778f6f49d };
switch (integral_type)
{
case cell:
  return integrals_cell_form_1b48ed2e66b63f65dfb298e72afaf2238490f388;
default:
  return NULL;
}
}

ufcx_form form_1b48ed2e66b63f65dfb298e72afaf2238490f388 =
{

  .signature = "100eae67a1d4a17ba3a30070349d7c552775172912108b2a5f8028edcd11451f465e7653a47cc750521d2af6b26b794904dae59d21046a930892e6d949453182",
  .rank = 2,
  .num_coefficients = 0,
  .num_constants = 0,
  .original_coefficient_position = NULL,

  .coefficient_name_map = coefficient_name_form_1b48ed2e66b63f65dfb298e72afaf2238490f388,
  .constant_name_map = constant_name_form_1b48ed2e66b63f65dfb298e72afaf2238490f388,

  .finite_elements = finite_elements_form_1b48ed2e66b63f65dfb298e72afaf2238490f388,
  .dofmaps = dofmaps_form_1b48ed2e66b63f65dfb298e72afaf2238490f388,

  .integral_ids = integral_ids_form_1b48ed2e66b63f65dfb298e72afaf2238490f388,
  .num_integrals = num_integrals_form_1b48ed2e66b63f65dfb298e72afaf2238490f388,

  .integrals = integrals_form_1b48ed2e66b63f65dfb298e72afaf2238490f388
};

// Alias name
ufcx_form* form_ufl_formulation_a = &form_1b48ed2e66b63f65dfb298e72afaf2238490f388;

ufcx_function_space* functionspace_form_ufl_formulation_a(const char* function_name)
{
static ufcx_function_space functionspace_v =
{
.finite_element = &element_1e49afa206707d093aa7a304ac40b15c9118976c,
.dofmap = &dofmap_1e49afa206707d093aa7a304ac40b15c9118976c,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 1
};
static ufcx_function_space functionspace_u =
{
.finite_element = &element_1e49afa206707d093aa7a304ac40b15c9118976c,
.dofmap = &dofmap_1e49afa206707d093aa7a304ac40b15c9118976c,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 1
};
if (strcmp(function_name, "v") == 0)
  return &functionspace_v;
else if (strcmp(function_name, "u") == 0)
  return &functionspace_u;
return NULL;

}

// End of code for form form_1b48ed2e66b63f65dfb298e72afaf2238490f388

// Code for form form_cece1beaaf5522934b9579ac83dec923c9b4f4db

int original_coefficient_position_form_cece1beaaf5522934b9579ac83dec923c9b4f4db[2] = { 0, 1 };
ufcx_dofmap* dofmaps_form_cece1beaaf5522934b9579ac83dec923c9b4f4db[3] = { &dofmap_1e49afa206707d093aa7a304ac40b15c9118976c, &dofmap_cf15df922a09e79fc4974dae41db8acb96787533, &dofmap_758f5686b8ddc30826def622d3335ea7a2de6406 };
ufcx_finite_element* finite_elements_form_cece1beaaf5522934b9579ac83dec923c9b4f4db[3] = { &element_1e49afa206707d093aa7a304ac40b15c9118976c, &element_cf15df922a09e79fc4974dae41db8acb96787533, &element_758f5686b8ddc30826def622d3335ea7a2de6406 };

// Return a list of the coefficient names.
const char** coefficient_name_form_cece1beaaf5522934b9579ac83dec923c9b4f4db(void)
{
static const char* names[2] = { "f", "g" };
return names;
}

// Return a list of the constant names.
const char** constant_name_form_cece1beaaf5522934b9579ac83dec923c9b4f4db(void)
{
return NULL;
}

int* integral_ids_form_cece1beaaf5522934b9579ac83dec923c9b4f4db(ufcx_integral_type integral_type)
{
static int integral_ids_cell_form_cece1beaaf5522934b9579ac83dec923c9b4f4db[1] = { -1 };
switch (integral_type)
{
case cell:
  return integral_ids_cell_form_cece1beaaf5522934b9579ac83dec923c9b4f4db;
default:
  return NULL;
}
}

int num_integrals_form_cece1beaaf5522934b9579ac83dec923c9b4f4db(ufcx_integral_type integral_type)
{
switch (integral_type)
{
case cell:
  return 1;
case interior_facet:
  return 0;
case exterior_facet:
  return 0;
default:
  return 0;
}
}

ufcx_integral** integrals_form_cece1beaaf5522934b9579ac83dec923c9b4f4db(ufcx_integral_type integral_type)
{
static ufcx_integral* integrals_cell_form_cece1beaaf5522934b9579ac83dec923c9b4f4db[1] = { &integral_a85408121493aa38ac6bbaa3b690511a8a9f5c0c };
switch (integral_type)
{
case cell:
  return integrals_cell_form_cece1beaaf5522934b9579ac83dec923c9b4f4db;
default:
  return NULL;
}
}

ufcx_form form_cece1beaaf5522934b9579ac83dec923c9b4f4db =
{

  .signature = "1052c20f48bf09236076e143a05ae6053cb8949e0757ea5581562b9c58f56a83e3b1b5793481806848d7a99252cbd458b87d603ba6f81346bc93022aca006c0c",
  .rank = 1,
  .num_coefficients = 2,
  .num_constants = 0,
  .original_coefficient_position = original_coefficient_position_form_cece1beaaf5522934b9579ac83dec923c9b4f4db,

  .coefficient_name_map = coefficient_name_form_cece1beaaf5522934b9579ac83dec923c9b4f4db,
  .constant_name_map = constant_name_form_cece1beaaf5522934b9579ac83dec923c9b4f4db,

  .finite_elements = finite_elements_form_cece1beaaf5522934b9579ac83dec923c9b4f4db,
  .dofmaps = dofmaps_form_cece1beaaf5522934b9579ac83dec923c9b4f4db,

  .integral_ids = integral_ids_form_cece1beaaf5522934b9579ac83dec923c9b4f4db,
  .num_integrals = num_integrals_form_cece1beaaf5522934b9579ac83dec923c9b4f4db,

  .integrals = integrals_form_cece1beaaf5522934b9579ac83dec923c9b4f4db
};

// Alias name
ufcx_form* form_ufl_formulation_L = &form_cece1beaaf5522934b9579ac83dec923c9b4f4db;

ufcx_function_space* functionspace_form_ufl_formulation_L(const char* function_name)
{
static ufcx_function_space functionspace_v =
{
.finite_element = &element_1e49afa206707d093aa7a304ac40b15c9118976c,
.dofmap = &dofmap_1e49afa206707d093aa7a304ac40b15c9118976c,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 1
};
static ufcx_function_space functionspace_f =
{
.finite_element = &element_cf15df922a09e79fc4974dae41db8acb96787533,
.dofmap = &dofmap_cf15df922a09e79fc4974dae41db8acb96787533,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 1
};
static ufcx_function_space functionspace_g =
{
.finite_element = &element_758f5686b8ddc30826def622d3335ea7a2de6406,
.dofmap = &dofmap_758f5686b8ddc30826def622d3335ea7a2de6406,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 1
};
if (strcmp(function_name, "v") == 0)
  return &functionspace_v;
else if (strcmp(function_name, "f") == 0)
  return &functionspace_f;
else if (strcmp(function_name, "g") == 0)
  return &functionspace_g;
return NULL;

}

// End of code for form form_cece1beaaf5522934b9579ac83dec923c9b4f4db
