// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.6.0.
//
// This code was generated with the following options:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '/root/shared/src',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['/root/shared/src/ufl_formulation.py'],
//   'verbosity': 30,
//   'visualise': True}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_758f5686b8ddc30826def622d3335ea7a2de6406;

extern ufcx_finite_element element_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7;

extern ufcx_finite_element element_1e49afa206707d093aa7a304ac40b15c9118976c;

extern ufcx_finite_element element_cf15df922a09e79fc4974dae41db8acb96787533;

extern ufcx_dofmap dofmap_758f5686b8ddc30826def622d3335ea7a2de6406;

extern ufcx_dofmap dofmap_81124ca14e6d0ff6f1e9f0d8369184bd0adfbae7;

extern ufcx_dofmap dofmap_1e49afa206707d093aa7a304ac40b15c9118976c;

extern ufcx_dofmap dofmap_cf15df922a09e79fc4974dae41db8acb96787533;

extern ufcx_integral integral_d6d1f05c892850147487cbd2aced82d778f6f49d;

extern ufcx_integral integral_a85408121493aa38ac6bbaa3b690511a8a9f5c0c;

extern ufcx_form form_1b48ed2e66b63f65dfb298e72afaf2238490f388;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_ufl_formulation_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_ufl_formulation_a(const char* function_name);

extern ufcx_form form_cece1beaaf5522934b9579ac83dec923c9b4f4db;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_ufl_formulation_L;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_ufl_formulation_L(const char* function_name);

#ifdef __cplusplus
}
#endif
