
// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.8.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'output_directory': '/root/shared/src',
//   'profile': False,
//   'scalar_type': 'float64',
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'ufl_file': ['/root/shared/src/ufl_formulation.py'],
//   'verbosity': 30,
//   'visualise': True}

#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>



// Code for element element_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe






ufcx_finite_element element_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe =
{
  .signature = "Basix element (P, triangle, 0, gll_warped, unset, True, float64, [])",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .space_dimension = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 0,
  .symmetric = false,
  .block_size = 1,
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = true,
  .lagrange_variant = 2,
  .dpc_variant = 0,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL,
  .custom_quadrature = NULL
};

// End of code for element element_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe

// Code for element element_e60371328a49148d7039c103115050855ae79a18






ufcx_finite_element element_e60371328a49148d7039c103115050855ae79a18 =
{
  .signature = "Basix element (P, triangle, 1, gll_warped, unset, False, float64, [])",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .space_dimension = 3,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .symmetric = false,
  .block_size = 1,
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 2,
  .dpc_variant = 0,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL,
  .custom_quadrature = NULL
};

// End of code for element element_e60371328a49148d7039c103115050855ae79a18

// Code for element element_9c6cd84bfc267751ad970123baa9b98e3391e3e7

int reference_value_shape_element_9c6cd84bfc267751ad970123baa9b98e3391e3e7[1] = {2};
ufcx_finite_element* sub_elements_element_9c6cd84bfc267751ad970123baa9b98e3391e3e7[2] = {&element_e60371328a49148d7039c103115050855ae79a18, &element_e60371328a49148d7039c103115050855ae79a18};



ufcx_finite_element element_9c6cd84bfc267751ad970123baa9b98e3391e3e7 =
{
  .signature = "blocked element (Basix element (P, triangle, 1, gll_warped, unset, False, float64, []), (2,))",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .space_dimension = 6,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_9c6cd84bfc267751ad970123baa9b98e3391e3e7,
  .reference_value_size = 2,
  .degree = 1,
  .symmetric = false,
  .block_size = 2,
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 2,
  .dpc_variant = 0,
  .num_sub_elements = 2,
  .sub_elements = sub_elements_element_9c6cd84bfc267751ad970123baa9b98e3391e3e7,
  .custom_element = NULL,
  .custom_quadrature = NULL
};

// End of code for element element_9c6cd84bfc267751ad970123baa9b98e3391e3e7

// Code for element element_f4f67755fd7baf4a3b706b45903ee041f79a5f4e






ufcx_finite_element element_f4f67755fd7baf4a3b706b45903ee041f79a5f4e =
{
  .signature = "Basix element (P, triangle, 2, gll_warped, unset, True, float64, [])",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .space_dimension = 6,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 2,
  .symmetric = false,
  .block_size = 1,
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = true,
  .lagrange_variant = 2,
  .dpc_variant = 0,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL,
  .custom_quadrature = NULL
};

// End of code for element element_f4f67755fd7baf4a3b706b45903ee041f79a5f4e

// Code for dofmap dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe



int entity_dofs_dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe[1] = {0};

int entity_dof_offsets_dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe[8] = {0, 0, 0, 0, 0, 0, 0, 1};

int entity_closure_dofs_dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe[1] = {0};

int entity_closure_dof_offsets_dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe[8] = {0, 0, 0, 0, 0, 0, 0, 1};

ufcx_dofmap dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 0, gll_warped, unset, True, float64, [])",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 1,
  .block_size = 1,
  .entity_dofs = entity_dofs_dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe,
  .entity_dof_offsets = entity_dof_offsets_dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe,
  .entity_closure_dofs = entity_closure_dofs_dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe

// Code for dofmap dofmap_e60371328a49148d7039c103115050855ae79a18



int entity_dofs_dofmap_e60371328a49148d7039c103115050855ae79a18[3] = {0, 1, 2};

int entity_dof_offsets_dofmap_e60371328a49148d7039c103115050855ae79a18[8] = {0, 1, 2, 3, 3, 3, 3, 3};

int entity_closure_dofs_dofmap_e60371328a49148d7039c103115050855ae79a18[12] = {0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2};

int entity_closure_dof_offsets_dofmap_e60371328a49148d7039c103115050855ae79a18[8] = {0, 1, 2, 3, 5, 7, 9, 12};

ufcx_dofmap dofmap_e60371328a49148d7039c103115050855ae79a18 =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 1, gll_warped, unset, False, float64, [])",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 1,
  .entity_dofs = entity_dofs_dofmap_e60371328a49148d7039c103115050855ae79a18,
  .entity_dof_offsets = entity_dof_offsets_dofmap_e60371328a49148d7039c103115050855ae79a18,
  .entity_closure_dofs = entity_closure_dofs_dofmap_e60371328a49148d7039c103115050855ae79a18,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_e60371328a49148d7039c103115050855ae79a18,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_e60371328a49148d7039c103115050855ae79a18

// Code for dofmap dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7

ufcx_dofmap* sub_dofmaps_dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7[2] = {&dofmap_e60371328a49148d7039c103115050855ae79a18, &dofmap_e60371328a49148d7039c103115050855ae79a18};

int entity_dofs_dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7[3] = {0, 1, 2};

int entity_dof_offsets_dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7[8] = {0, 1, 2, 3, 3, 3, 3, 3};

int entity_closure_dofs_dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7[12] = {0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2};

int entity_closure_dof_offsets_dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7[8] = {0, 1, 2, 3, 5, 7, 9, 12};

ufcx_dofmap dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7 =
{
  .signature = "FFCx dofmap for blocked element (Basix element (P, triangle, 1, gll_warped, unset, False, float64, []), (2,))",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 2,
  .entity_dofs = entity_dofs_dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7,
  .entity_dof_offsets = entity_dof_offsets_dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7,
  .entity_closure_dofs = entity_closure_dofs_dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7,
  .num_sub_dofmaps = 2,
  .sub_dofmaps = sub_dofmaps_dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7
};

// End of code for dofmap dofmap_9c6cd84bfc267751ad970123baa9b98e3391e3e7

// Code for dofmap dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e



int entity_dofs_dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e[6] = {0, 1, 2, 3, 4, 5};

int entity_dof_offsets_dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e[8] = {0, 0, 0, 0, 0, 0, 0, 6};

int entity_closure_dofs_dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e[6] = {0, 1, 2, 3, 4, 5};

int entity_closure_dof_offsets_dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e[8] = {0, 0, 0, 0, 0, 0, 0, 6};

ufcx_dofmap dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 2, gll_warped, unset, True, float64, [])",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 6,
  .block_size = 1,
  .entity_dofs = entity_dofs_dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e,
  .entity_dof_offsets = entity_dof_offsets_dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e,
  .entity_closure_dofs = entity_closure_dofs_dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e

// Code for integral integral_444ae3de485a81d987c5e8c21247536bf812e211

void tabulate_tensor_integral_444ae3de485a81d987c5e8c21247536bf812e211(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
// Quadrature rules
static const double weights_39d[6] = {0.054975871827661, 0.054975871827661, 0.054975871827661, 0.1116907948390055, 0.1116907948390055, 0.1116907948390055};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const double FE1_C0_D10_Q39d[1][1][1][3] = {{{{-1.0, 1.0, 0.0}}}};
static const double FE1_C1_D01_Q39d[1][1][1][3] = {{{{-1.0, 0.0, 1.0}}}};
static const double FE2_C0_Q39d[1][1][6][6] = {{{{-0.07480380774819603, 0.5176323419876736, -0.07480380774819671, 0.2992152309927871, 0.03354481152314834, 0.2992152309927839},
  {-0.07480380774819613, -0.0748038077481966, 0.5176323419876735, 0.2992152309927871, 0.2992152309927838, 0.03354481152314828},
  {0.5176323419876713, -0.0748038077481967, -0.07480380774819674, 0.03354481152314866, 0.2992152309927869, 0.2992152309927868},
  {-0.04820837781551195, -0.08473049309397784, -0.04820837781551192, 0.1928335112620479, 0.7954802262009061, 0.1928335112620478},
  {-0.04820837781551193, -0.048208377815512, -0.08473049309397786, 0.1928335112620479, 0.192833511262048, 0.7954802262009062},
  {-0.08473049309397794, -0.04820837781551188, -0.04820837781551195, 0.7954802262009061, 0.1928335112620479, 0.1928335112620479}}}};
// ------------------------ 
// Section: Jacobian
// Inputs: coordinate_dofs, FE1_C0_D10_Q39d, FE1_C1_D01_Q39d
// Outputs: J_c2, J_c1, J_c3, J_c0
double J_c0 = 0.0;
double J_c3 = 0.0;
double J_c1 = 0.0;
double J_c2 = 0.0;
{
  for (int ic = 0; ic < 3; ++ic)
  {
    J_c0 += coordinate_dofs[(ic) * 3] * FE1_C0_D10_Q39d[0][0][0][ic];
    J_c3 += coordinate_dofs[(ic) * 3 + 1] * FE1_C1_D01_Q39d[0][0][0][ic];
    J_c1 += coordinate_dofs[(ic) * 3] * FE1_C1_D01_Q39d[0][0][0][ic];
    J_c2 += coordinate_dofs[(ic) * 3 + 1] * FE1_C0_D10_Q39d[0][0][0][ic];
  }
}
// ------------------------ 
double sp_39d_0 = J_c0 * J_c3;
double sp_39d_1 = J_c1 * J_c2;
double sp_39d_2 = -sp_39d_1;
double sp_39d_3 = sp_39d_0 + sp_39d_2;
double sp_39d_4 = fabs(sp_39d_3);
for (int iq = 0; iq < 6; ++iq)
{
  // ------------------------ 
  // Section: Intermediates
  // Inputs: 
  // Outputs: fw0
  double fw0 = 0;
  {
    fw0 = sp_39d_4 * weights_39d[iq];
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Tensor Computation
  // Inputs: fw0, FE2_C0_Q39d
  // Outputs: A
  {
    double temp_0[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_0[j] = fw0 * FE2_C0_Q39d[0][0][iq][j];
    }
    for (int j = 0; j < 6; ++j)
    {
      for (int i = 0; i < 6; ++i)
      {
        A[6 * (i) + (j)] += FE2_C0_Q39d[0][0][iq][i] * temp_0[j];
      }
    }
  }
  // ------------------------ 
}

}



ufcx_integral integral_444ae3de485a81d987c5e8c21247536bf812e211 =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor_float32 = NULL,
  .tabulate_tensor_float64 = tabulate_tensor_integral_444ae3de485a81d987c5e8c21247536bf812e211,
  .tabulate_tensor_complex64 = NULL,
  .tabulate_tensor_complex128 = NULL,
  .needs_facet_permutations = false,
  .coordinate_element = &element_9c6cd84bfc267751ad970123baa9b98e3391e3e7,
};

// End of code for integral integral_444ae3de485a81d987c5e8c21247536bf812e211

// Code for integral integral_5fffa26f3a123822642449d4060dea801aa7395e

void tabulate_tensor_integral_5fffa26f3a123822642449d4060dea801aa7395e(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
// Quadrature rules
static const double weights_7a4[6] = {0.08333333333333333, 0.08333333333333333, 0.08333333333333333, 0.08333333333333333, 0.08333333333333333, 0.08333333333333333};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const double FE1_C0_Q7a4[1][1][6][3] = {{{{0.1090390090728771, 0.659027622374092, 0.231933368553031},
  {0.2319333685530311, 0.659027622374092, 0.109039009072877},
  {0.109039009072877, 0.231933368553031, 0.6590276223740918},
  {0.6590276223740921, 0.231933368553031, 0.109039009072877},
  {0.231933368553031, 0.109039009072877, 0.6590276223740918},
  {0.6590276223740921, 0.1090390090728769, 0.231933368553031}}}};
static const double FE2_C0_D10_Q7a4[1][1][1][3] = {{{{-1.0, 1.0, 0.0}}}};
static const double FE2_C1_D01_Q7a4[1][1][1][3] = {{{{-1.0, 0.0, 1.0}}}};
static const double FE3_C0_Q7a4[1][1][6][6] = {{{{-0.08525999807368716, 0.2096071917300056, -0.1243471936563188, 0.6114019857068721, 0.1011591387118275, 0.2874388755813007},
  {-0.1243471936563188, 0.2096071917300055, -0.08525999807368713, 0.2874388755813008, 0.1011591387118276, 0.6114019857068723},
  {-0.0852599980736872, -0.1243471936563187, 0.2096071917300056, 0.6114019857068721, 0.2874388755813007, 0.1011591387118275},
  {0.2096071917300056, -0.1243471936563188, -0.08525999807368713, 0.1011591387118276, 0.2874388755813008, 0.6114019857068723},
  {-0.1243471936563188, -0.08525999807368707, 0.2096071917300056, 0.2874388755813007, 0.6114019857068721, 0.1011591387118275},
  {0.2096071917300057, -0.08525999807368712, -0.1243471936563187, 0.1011591387118275, 0.6114019857068722, 0.2874388755813007}}}};
// ------------------------ 
// Section: Jacobian
// Inputs: coordinate_dofs, FE2_C1_D01_Q7a4, FE2_C0_D10_Q7a4
// Outputs: J_c2, J_c1, J_c3, J_c0
double J_c0 = 0.0;
double J_c3 = 0.0;
double J_c1 = 0.0;
double J_c2 = 0.0;
{
  for (int ic = 0; ic < 3; ++ic)
  {
    J_c0 += coordinate_dofs[(ic) * 3] * FE2_C0_D10_Q7a4[0][0][0][ic];
    J_c3 += coordinate_dofs[(ic) * 3 + 1] * FE2_C1_D01_Q7a4[0][0][0][ic];
    J_c1 += coordinate_dofs[(ic) * 3] * FE2_C1_D01_Q7a4[0][0][0][ic];
    J_c2 += coordinate_dofs[(ic) * 3 + 1] * FE2_C0_D10_Q7a4[0][0][0][ic];
  }
}
// ------------------------ 
double sp_7a4_0 = J_c0 * J_c3;
double sp_7a4_1 = J_c1 * J_c2;
double sp_7a4_2 = -sp_7a4_1;
double sp_7a4_3 = sp_7a4_0 + sp_7a4_2;
double sp_7a4_4 = fabs(sp_7a4_3);
for (int iq = 0; iq < 6; ++iq)
{
  // ------------------------ 
  // Section: Coefficient
  // Inputs: FE1_C0_Q7a4, w
  // Outputs: w1
  double w1 = 0.0;
  {
    for (int ic = 0; ic < 3; ++ic)
    {
      w1 += w[1 + (ic)] * FE1_C0_Q7a4[0][0][iq][ic];
    }
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Intermediates
  // Inputs: w1
  // Outputs: fw0
  double fw0 = 0;
  {
    double sv_7a4_0 = w[0] / w1;
    double sv_7a4_1 = sv_7a4_0 * sp_7a4_4;
    fw0 = sv_7a4_1 * weights_7a4[iq];
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Tensor Computation
  // Inputs: FE3_C0_Q7a4, fw0
  // Outputs: A
  {
    for (int i = 0; i < 6; ++i)
    {
      A[(i)] += fw0 * FE3_C0_Q7a4[0][0][iq][i];
    }
  }
  // ------------------------ 
}

}

bool enabled_coefficients_integral_5fffa26f3a123822642449d4060dea801aa7395e[2] = {1, 1};

ufcx_integral integral_5fffa26f3a123822642449d4060dea801aa7395e =
{
  .enabled_coefficients = enabled_coefficients_integral_5fffa26f3a123822642449d4060dea801aa7395e,
  .tabulate_tensor_float32 = NULL,
  .tabulate_tensor_float64 = tabulate_tensor_integral_5fffa26f3a123822642449d4060dea801aa7395e,
  .tabulate_tensor_complex64 = NULL,
  .tabulate_tensor_complex128 = NULL,
  .needs_facet_permutations = false,
  .coordinate_element = &element_9c6cd84bfc267751ad970123baa9b98e3391e3e7,
};

// End of code for integral integral_5fffa26f3a123822642449d4060dea801aa7395e

// Code for form form_90f642a9a6a793322d73d559b0f550b853e94484


ufcx_dofmap* dofmaps_form_90f642a9a6a793322d73d559b0f550b853e94484[2] = {&dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e, &dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e};
ufcx_finite_element* finite_elements_form_90f642a9a6a793322d73d559b0f550b853e94484[2] = {&element_f4f67755fd7baf4a3b706b45903ee041f79a5f4e, &element_f4f67755fd7baf4a3b706b45903ee041f79a5f4e};
int form_integral_offsets_form_90f642a9a6a793322d73d559b0f550b853e94484[4] = {0, 1, 1, 1};
static ufcx_integral* form_integrals_form_90f642a9a6a793322d73d559b0f550b853e94484[1] = {&integral_444ae3de485a81d987c5e8c21247536bf812e211};
int form_integral_ids_form_90f642a9a6a793322d73d559b0f550b853e94484[1] = {-1};




ufcx_form form_90f642a9a6a793322d73d559b0f550b853e94484 =
{

  .signature = "659bb7829ca998ae070c00d61791dc81c948b9e100543c733f60e485fa28787eed5c6d044ab581f3b1066a171205e3e71c8e80ac6c6bec35ce596fd00f6551de",
  .rank = 2,
  .num_coefficients = 0,
  .num_constants = 0,
  .original_coefficient_position = NULL,

  .coefficient_name_map = NULL,
  .constant_name_map = NULL,

  .finite_elements = finite_elements_form_90f642a9a6a793322d73d559b0f550b853e94484,
  .dofmaps = dofmaps_form_90f642a9a6a793322d73d559b0f550b853e94484,

  .form_integrals = form_integrals_form_90f642a9a6a793322d73d559b0f550b853e94484,
  .form_integral_ids = form_integral_ids_form_90f642a9a6a793322d73d559b0f550b853e94484,
  .form_integral_offsets = form_integral_offsets_form_90f642a9a6a793322d73d559b0f550b853e94484
};

// Alias name
ufcx_form* form_ufl_formulation_a = &form_90f642a9a6a793322d73d559b0f550b853e94484;


ufcx_function_space* functionspace_form_ufl_formulation_a(const char* function_name)
{
static ufcx_function_space functionspace_v =
{
.finite_element = &element_f4f67755fd7baf4a3b706b45903ee041f79a5f4e,
.dofmap = &dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 2,
.value_rank = 0,
.value_shape = NULL
};
static ufcx_function_space functionspace_u =
{
.finite_element = &element_f4f67755fd7baf4a3b706b45903ee041f79a5f4e,
.dofmap = &dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 2,
.value_rank = 0,
.value_shape = NULL
};
if (strcmp(function_name, "v") == 0) return &functionspace_v;
if (strcmp(function_name, "u") == 0) return &functionspace_u;
return NULL;

}

// End of code for form form_90f642a9a6a793322d73d559b0f550b853e94484

// Code for form form_9c888822c24f02117cf7026f8906d26c9161e223

int original_coefficient_position_form_9c888822c24f02117cf7026f8906d26c9161e223[2] = {0, 1};
ufcx_dofmap* dofmaps_form_9c888822c24f02117cf7026f8906d26c9161e223[3] = {&dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e, &dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe, &dofmap_e60371328a49148d7039c103115050855ae79a18};
ufcx_finite_element* finite_elements_form_9c888822c24f02117cf7026f8906d26c9161e223[3] = {&element_f4f67755fd7baf4a3b706b45903ee041f79a5f4e, &element_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe, &element_e60371328a49148d7039c103115050855ae79a18};
int form_integral_offsets_form_9c888822c24f02117cf7026f8906d26c9161e223[4] = {0, 1, 1, 1};
static ufcx_integral* form_integrals_form_9c888822c24f02117cf7026f8906d26c9161e223[1] = {&integral_5fffa26f3a123822642449d4060dea801aa7395e};
int form_integral_ids_form_9c888822c24f02117cf7026f8906d26c9161e223[1] = {-1};

static const char* coefficient_names_form_9c888822c24f02117cf7026f8906d26c9161e223[2] = {"f", "g"};


ufcx_form form_9c888822c24f02117cf7026f8906d26c9161e223 =
{

  .signature = "c69b7c4d33d120b5b88aa5ecf30f377f9a2a5e69db12cb9de10ed33b9e7375c40c009a9811af8c64ffe0bf8b3b5a2e0b434ad4a65eedc8b3d5b29256245bf687",
  .rank = 1,
  .num_coefficients = 2,
  .num_constants = 0,
  .original_coefficient_position = original_coefficient_position_form_9c888822c24f02117cf7026f8906d26c9161e223,

  .coefficient_name_map = coefficient_names_form_9c888822c24f02117cf7026f8906d26c9161e223,
  .constant_name_map = NULL,

  .finite_elements = finite_elements_form_9c888822c24f02117cf7026f8906d26c9161e223,
  .dofmaps = dofmaps_form_9c888822c24f02117cf7026f8906d26c9161e223,

  .form_integrals = form_integrals_form_9c888822c24f02117cf7026f8906d26c9161e223,
  .form_integral_ids = form_integral_ids_form_9c888822c24f02117cf7026f8906d26c9161e223,
  .form_integral_offsets = form_integral_offsets_form_9c888822c24f02117cf7026f8906d26c9161e223
};

// Alias name
ufcx_form* form_ufl_formulation_L = &form_9c888822c24f02117cf7026f8906d26c9161e223;


ufcx_function_space* functionspace_form_ufl_formulation_L(const char* function_name)
{
static ufcx_function_space functionspace_v =
{
.finite_element = &element_f4f67755fd7baf4a3b706b45903ee041f79a5f4e,
.dofmap = &dofmap_f4f67755fd7baf4a3b706b45903ee041f79a5f4e,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 2,
.value_rank = 0,
.value_shape = NULL
};
static ufcx_function_space functionspace_f =
{
.finite_element = &element_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe,
.dofmap = &dofmap_74d6cdfde3ea4b5d423c7bf4310320a0acafddfe,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 2,
.value_rank = 0,
.value_shape = NULL
};
static ufcx_function_space functionspace_g =
{
.finite_element = &element_e60371328a49148d7039c103115050855ae79a18,
.dofmap = &dofmap_e60371328a49148d7039c103115050855ae79a18,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 2,
.value_rank = 0,
.value_shape = NULL
};
if (strcmp(function_name, "v") == 0) return &functionspace_v;
if (strcmp(function_name, "f") == 0) return &functionspace_f;
if (strcmp(function_name, "g") == 0) return &functionspace_g;
return NULL;

}

// End of code for form form_9c888822c24f02117cf7026f8906d26c9161e223
