
// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.10.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'output_directory': '/root/shared/src',
//   'part': 'full',
//   'profile': False,
//   'scalar_type': 'float64',
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'ufl_file': ['/root/shared/src/ufl_formulation.py'],
//   'verbosity': 30,
//   'visualise': True}

#pragma once
#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_integral integral_3ab73ccaefcd8273fa990fe5ec63e07b7e9a5c8f_triangle;

extern ufcx_integral integral_6f3b446499f16f37029e8ce6745512f65fab2937_triangle;

extern ufcx_form form_e9cfbc1cc6e22bb5d43d61ffc1ec480a24b6b1e2;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_ufl_formulation_a;


extern ufcx_form form_966d9175b91d7b49df7ca32ab0b3ee2517e99d6d;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_ufl_formulation_L;


#ifdef __cplusplus
}
#endif
